---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Swamp Jaguar")
AddNameToAvoidWhiteList("Adolescent Whelp")
AddNameToAvoidWhiteList("Adolescent Whelp")
AddNameToAvoidWhiteList("Sorrow Spinner")
AddNameToAvoidWhiteList("Dreaming Whelp")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 767
IDs[2] = 740
IDs[3] = 740
IDs[4] = 858
IDs[5] = 741
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -10565.05
StartingPoint[2] = -2507.308
StartingPoint[3] = 22.22653
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),150,StartingFloat, true)