---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Angerclaw Bear")
AddNameToAvoidWhiteList("Felpaw Wolf")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 8956
IDs[2] = 8959
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 4127.974
StartingPoint[2] = -1140.844
StartingPoint[3] = 294.2253
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),500,StartingFloat, true)