---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Highborne Apparition")
AddNameToAvoidWhiteList("Highborne Lichling")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 6116
IDs[2] = 6117
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 2816.11
StartingPoint[2] = -3955.566
StartingPoint[3] = 97.06125
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),400,StartingFloat, true)