---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Scalding Whelp")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 2725
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = -6397.214
StartingPoint[2] = -3979.549
StartingPoint[3] = 267.3589
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),275,StartingFloat, true)