---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Suffering Highborne")
AddNameToAvoidWhiteList("Anguished Highborne")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 7523
IDs[2] = 7524
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 6500.276
StartingPoint[2] = -4164.089
StartingPoint[3] = 658.7799
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat)