---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Felpaw Ravager")
AddNameToAvoidWhiteList("Angerclaw Grizzly")
AddNameToAvoidWhiteList("Ironbeak Screecher")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 8961
IDs[2] = 8957
IDs[3] = 7098
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 6451.649
StartingPoint[2] = -2017.19
StartingPoint[3] = 569.7339
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat, true)