---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Warpwood Shredder")
AddNameToAvoidWhiteList("Warpwood Moss Flayer")
StartMobAvoidance()

local InRangeSpawns = {}
local IDs = {}
IDs[1] = 7101
IDs[2] = 7100
--Starting Point--
local StartingPoint = {}
StartingPoint[1] = 6503.327
StartingPoint[2] = -1524.349
StartingPoint[3] = 440.292
StartingFloat = TableToFloatArray(StartingPoint)
GrindAndGather(TableToList(IDs),300,StartingFloat, true)